Fix deployment (in and out of docker)
ENOFLAG/ENOKEY pull request #26
Opened 2019-02-07 20:53 UTC by Trolldemorted

2019-02-10 15:42 UTC, fsck requested changes

2019-02-10 15:42 UTC, fsck commented on docker-compose.yml
> +      - SERVER_ADMIN=benni@benni.stronk.pw:8022
I feel like this field should be filled with clear example hostnames or (preferably) we should add some testing code for launching a local sshd and then point to that.

2019-02-10 15:42 UTC, fsck commented on src/deploy.rs
> +            .args(&["-i", "./data/id_ed25519",
I am not very happy with this solution but if you insist you need ed25519 keys and absolutely can not live with ecdsa keys than I will endure this. But maybe we can add some more differentiated error handling.

2019-02-10 15:42 UTC, fsck commented on src/storage.rs
> +        .args(&["-t", "ed25519", "-m", "pem", "-f", "./data/id_ed25519"])
This should be configurable options (which key[path] to use; whether it should be generate at startup, if not found)

2019-02-10 15:42 UTC, fsck commented on src/storage.rs
> +pub fn load_deploy_keypair() -> Result<(), EnokeysError> {
This function is a stub.

2019-02-10 16:06 UTC, Trolldemorted commented on docker-compose.yml
> +      - SERVER_ADMIN=benni@benni.stronk.pw:8022
Imho we shouldn't have a docker-compose.yml in this repository at all - an example yaml in the readme should be enough.

2019-02-10 16:07 UTC, Trolldemorted commented on src/deploy.rs
> +            .args(&["-i", "./data/id_ed25519",
You are welcome to implement deployment with ssh2 - I just kept it as simple as possible for the MVP.

2019-02-10 16:08 UTC, Trolldemorted commented on src/storage.rs
> +        .args(&["-t", "ed25519", "-m", "pem", "-f", "./data/id_ed25519"])
Is that within the scope of this PR?

2019-02-10 16:14 UTC, Trolldemorted commented on src/storage.rs
> +pub fn load_deploy_keypair() -> Result<(), EnokeysError> {
Obviously - I kept it here until a deploy key management decision is there.

2019-02-26 15:34 UTC, fsck commented
Rolled into #28

2019-02-26 15:34 UTC, closed without merging