[WIP] Add an adhoc fairing to include additional headers in responses
ENOFLAG/ENOKEY pull request #45
Opened 2019-03-02 15:16 UTC by fsck

Addresses #33

2019-03-02 18:37 UTC, Trolldemorted submitted a review, later dismissed
Lgtm, but I am certainly not an expert on http security headers, @domenukk should have a say

2019-03-03 12:35 UTC, domenukk requested changes
I added some comments about the headers.
AFAIK they are case sensitive... Also we can add more :)

2019-03-03 12:35 UTC, domenukk commented on src/main.rs
> +            resp.adjoin_raw_header("x-xss-protection", "1");
AFAIK Headers are Case Sensitive.
Also we would want to add the block directive here:
("X-Xss-Protection", "1; mode=block");

2019-03-03 12:35 UTC, domenukk commented on src/main.rs
> +            resp.adjoin_raw_header("x-frame-options", "SAMEORIGIN");
"X-Frame-Options" < case sensitive

2019-03-03 12:35 UTC, domenukk commented on src/main.rs
> +        }))
Two other handy headers:
("X-Content-Type-Options", "nosniff"); // Disables content sniffing for older browsers
("Referrer-Policy", "no-referrer-when-downgrade"); // won't send a referrer when going from https to http

2019-03-03 12:39 UTC, fsck commented on src/main.rs
> +            resp.adjoin_raw_header("x-xss-protection", "1");
In your link in #33 they have [example code](https://www.keycdn.com/blog/http-security-headers#2-x-xss-protection) in all lowercase.
[Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection) is referring to like this: "X-XSS-Protection: 1"

2019-03-03 12:50 UTC, domenukk commented on src/main.rs
> +            resp.adjoin_raw_header("x-xss-protection", "1");
I stand corrected. Still we want mode=block.

2019-03-03 12:50 UTC, domenukk commented on src/main.rs
> +            resp.adjoin_raw_header("x-frame-options", "SAMEORIGIN");
Apparently not. I stand corrected.

2019-03-03 12:51 UTC, fsck commented on src/main.rs
> +            resp.adjoin_raw_header("x-frame-options", "SAMEORIGIN");
Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive. [rfc2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2)

2019-03-03 12:52 UTC, fsck commented on src/main.rs
> +        }))
Sounds good, I will add them to the PR

2019-03-03 13:05 UTC, domenukk submitted a review, later dismissed

2019-03-03 13:07 UTC, domenukk submitted a review, later dismissed
looks good

2019-03-03 13:07 UTC, domenukk commented on src/main.rs
> +            resp.adjoin_raw_header("X-XSS-Protection", "1");
Still no "mode=block"

2019-03-03 13:10 UTC, fsck commented on src/main.rs
> +            resp.adjoin_raw_header("X-XSS-Protection", "1");
Should be fixed now

2019-03-03 13:11 UTC, fsck commented on src/main.rs
> +            resp.adjoin_raw_header("X-XSS-Protection", "1");
Sorry for the multiple force-pushes

2019-03-03 20:32 UTC, Trolldemorted approved these changes

2019-03-03 20:35 UTC, merged